name: Deployment process on main merge 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} > ~/.ssh/known_hosts
          
      - name: Connect and create TXT
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /root/org/ && echo 'hello' > hello.txt"

      - name: Cleanup
        run: rm -rf ~/.ssh
