name: Deployment process on main merge 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 172.234.108.148
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}  # Private SSH key stored in GitHub Secrets
          port: 22
          script: |
            cd /root/org/
            docker compose up -d  # Recreate containers with the latest image
